version: '2'

services:
  symfony:
    build: .
    links:
      - mysql:symfony_db
    environment:
      - DATABASE_HOST=symfony_db

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
